from __future__ import annotations

from typing import Any

DEFAULT_ELECTRICAL_SOURCE_KEYWORDS = [
    "electrical",
    "electric",
    "electrical systems",
    "electrical installations",
    "electric work",
    "battery electric",
    "battery-electric",
    "low voltage",
    "medium voltage",
    "high voltage",
    "shore power",
    "power hub",
    "power station",
    "cable",
    "conduit",
    "underground",
    "utility",
    "transformer",
    "substation",
    "switchgear",
    "fire alarm",
    "generator",
    "energization",
    "data center",
    "datacenter",
    "hyperscale",
    "colocation",
    "critical power",
    "ai infrastructure",
    "artificial intelligence",
    "hpc",
    "high performance computing",
    "gpu",
    "compute campus",
    "server farm",
    "ups",
    "uninterruptible power supply",
    "busduct",
    "busway",
    "power distribution unit",
    "utility interconnection",
    "battery storage",
    "renewable energy",
    "solar",
    "wind energy",
    "ev charger",
    "transmission",
    "distribution",
    "lighting",
    "lights",
    "airfield lights",
    "lighting infrastructure",
]

SAM_GOV_ELECTRICAL_SOURCE_KEYWORDS = [
    "electrical cable",
    "medium voltage",
    "high voltage",
    "underground cable",
    "overhead line",
    "pole line",
    "transmission",
    "distribution",
    "substation",
    "transformer",
    "switchgear",
    "conduit",
    "duct bank",
    "feeder",
    "fiber optic",
    "data center",
    "datacenter",
    "hyperscale",
    "colocation",
    "critical power",
    "ai infrastructure",
    "artificial intelligence",
    "hpc",
    "gpu",
    "compute campus",
    "ups",
    "busduct",
    "busway",
    "utility interconnection",
    "utility replacement",
]


def _catalog_entry(
    source: str,
    label: str,
    category: str,
    coverage: str,
    adapter: str,
    source_url: str | None = None,
    directory_only: bool = False,
    requires_setting: str | None = None,
    portal_gated: bool = False,
    access_note: str | None = None,
    covered_by_source: str | None = None,
    job_params: dict[str, Any] | None = None,
) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "source": source,
        "label": label,
        "category": category,
        "coverage": coverage,
        "adapter": adapter,
    }
    if source_url:
        entry["source_url"] = source_url
    if directory_only:
        entry["directory_only"] = True
    if requires_setting:
        entry["requires_setting"] = requires_setting
    if portal_gated:
        entry["portal_gated"] = True
    if access_note:
        entry["access_note"] = access_note
    if covered_by_source:
        entry["covered_by_source"] = covered_by_source
    if job_params:
        entry["job_params"] = job_params
    return entry


DEFAULT_SOURCE_CATALOG = [
    _catalog_entry("sam_gov", "SAM.gov", "federal", "Nationwide federal opportunities", "sam_gov", requires_setting="sam_gov_api_key"),
    _catalog_entry("txdot_bid_items", "TxDOT", "state_dot", "Texas statewide DOT lettings", "txdot_bid_items", "https://data.texas.gov/Transportation/Official-and-Unofficial-Bid-Items/qh8x-rm8r"),
    _catalog_entry("pa_emarketplace", "PA eMarketplace", "state_local", "Pennsylvania statewide open solicitations", "pa_emarketplace", "https://www.emarketplace.state.pa.us/Search.aspx/Home.aspx"),
    _catalog_entry("nypa", "NY Power Authority", "utility", "New York utility RFQ/RFPs", "nypa", "https://rfp.nypa.gov/", requires_setting="nypa_api_subscription_key"),
    _catalog_entry(
        "pjm_project_construction",
        "PJM Project Construction",
        "rto_iso",
        "PJM transmission upgrade project construction and cost allocation signals",
        "pjm_project_construction",
        "https://www.pjm.com/planning/m/project-construction",
    ),
    _catalog_entry(
        "caiso_interconnection_queue",
        "CAISO Interconnection Queue",
        "rto_iso",
        "CAISO interconnection queue reports for large generation, storage, and grid-impacting projects",
        "caiso_interconnection_queue",
        "https://www.caiso.com/library/interconnection-queue-reports",
    ),
    _catalog_entry(
        "ercot_capacity_changes",
        "ERCOT Planned Capacity",
        "rto_iso",
        "ERCOT planned resource capacity and interconnection signals, including data-center-adjacent grid load",
        "ercot_capacity_changes",
        "https://www.ercot.com/gridinfo/resource",
    ),
    _catalog_entry(
        "iso_ne_interconnection_queue",
        "ISO-NE Interconnection Queue",
        "rto_iso",
        "ISO New England public queue for generation, storage, ETU, and interconnection signals",
        "iso_ne_interconnection_queue",
        "https://www.iso-ne.com/system-planning/interconnection-service/interconnection-request-queue",
    ),
    _catalog_entry(
        "miso_eras_interconnection",
        "MISO ERAS Interconnection",
        "rto_iso",
        "MISO ERAS interconnection requests for early generation, storage, substation, and transmission-owner signals",
        "miso_eras_interconnection",
        "https://www.misoenergy.org/planning/resource-utilization/generator-interconnection/",
    ),
    _catalog_entry(
        "nyiso_interconnection_queue",
        "NYISO Interconnection Queue",
        "rto_iso",
        "NYISO public interconnection queue for large load, storage, generation, and transmission-owner signals",
        "nyiso_interconnection_queue",
        "https://www.nyiso.com/interconnections",
    ),
    _catalog_entry(
        "spp_gi_active_requests",
        "SPP GI Active Requests",
        "rto_iso",
        "Southwest Power Pool active generator interconnection requests and CSV queue signals",
        "spp_gi_active_requests",
        "https://spp.org/engineering/generator-interconnection/",
    ),
    _catalog_entry(
        "virginia_scc_transmission_cases",
        "Virginia SCC Transmission Cases",
        "regulatory",
        "Virginia State Corporation Commission CPCN and high-voltage transmission case signals",
        "virginia_scc_transmission_cases",
        "https://www.scc.virginia.gov/consumers/public-utility/electricity-faqs/transmission-line-projects/",
    ),
    _catalog_entry(
        "georgia_psc_data_center",
        "Georgia PSC Data Center",
        "regulatory",
        "Georgia Public Service Commission data-center large-load and Georgia Power planning signal",
        "georgia_psc_data_center",
        "https://psc.ga.gov/?lang=us",
    ),
    _catalog_entry(
        "texas_puc_dockets",
        "Texas PUCT Dockets",
        "regulatory",
        "Public Utility Commission of Texas electric dockets for CCN, transmission, and large-load proceedings",
        "texas_puc_dockets",
        "https://interchange.puc.texas.gov/search/dockets/?UtilityType=E&ItemMatch=Equal&DocumentType=ALL&SortBy=ControlNumber&SortOrder=Descending",
    ),
    _catalog_entry(
        "loudoun_land_applications",
        "Loudoun Land Applications",
        "land_use",
        "Loudoun County ArcGIS land application layer for data-center and industrial permitting signals",
        "loudoun_land_applications",
        "https://www.loudoun.gov/3362/Land-Application-Information-Comments",
    ),
    _catalog_entry("nyc_city_record", "NYC City Record", "state_local", "New York City public solicitations", "nyc_city_record"),
    _catalog_entry("nyc_school_construction_authority", "NYC School Construction", "education", "NYC School Construction Authority solicitations", "nyc_city_record"),
    _catalog_entry("la_ramp", "Los Angeles RAMP", "state_local", "Los Angeles city/county and LADWP-linked postings", "public_json_feed", "https://data.lacity.org/"),
    _catalog_entry("chicago_solicitations", "Chicago/CTA", "state_local", "City of Chicago and CTA solicitations", "chicago_solicitations"),
    _catalog_entry("sf_open_bids", "San Francisco", "state_local", "San Francisco open bid opportunities", "sf_open_bids"),
    _catalog_entry("montgomery_md_solicitations", "Montgomery County", "state_local", "Montgomery County, MD active solicitations", "public_json_feed"),
    _catalog_entry(
        "ca_dot",
        "Caltrans",
        "state_dot",
        "California state transportation bid opportunities",
        "public_portal_links",
        "https://caleprocure.ca.gov/",
        portal_gated=True,
        access_note="Cal eProcure currently returns an automated 403 response to server-side public monitoring.",
    ),
    _catalog_entry(
        "fl_dot",
        "FDOT",
        "state_dot",
        "Florida transportation lettings and procurement",
        "public_portal_links",
        "https://bqa.fdot.gov/proposal-search",
        portal_gated=True,
        access_note="FDOT proposal search is a public Angular app; use the official app API or browser session adapter after endpoint contract is verified.",
    ),
    _catalog_entry(
        "ny_dot",
        "NYSDOT",
        "state_dot",
        "New York transportation contract opportunities",
        "public_bid_page",
        "https://www.dot.ny.gov/doing-business/opportunities/const-notices",
        job_params={
            "candidate_selectors": ["table#myTable tr"],
            "title_column": 0,
            "due_date_column": 1,
            "source_url_column": 0,
            "source_url_pattern": r"const-contract-docs",
            "title_template": "NYSDOT contract {title}",
            "description_prefix": "NYSDOT construction opportunity.",
            "require_keywords": False,
            "require_procurement_terms": False,
            "limit": 50,
        },
    ),
    _catalog_entry(
        "ga_dot",
        "GDOT",
        "state_dot",
        "Georgia transportation bid opportunities",
        "public_portal_links",
        "https://solicitation.dot.ga.gov/",
        portal_gated=True,
        access_note="GDOT solicitation access requires log in / registration; use approved account access or an official feed.",
    ),
    _catalog_entry("il_dot", "IDOT", "state_dot", "Illinois transportation lettings and bids", "public_portal_links", "https://idot.illinois.gov/doing-business/procurements.html"),
    _catalog_entry(
        "oh_dot",
        "Ohio DOT / OhioBuys",
        "state_dot",
        "Ohio transportation bid opportunities through OhioBuys public solicitations",
        "public_portal_links",
        "https://ohiobuys.ohio.gov/page.aspx/en/rfp/request_browse_public",
        portal_gated=True,
        access_note="OhioBuys serves a browser/captcha check before public solicitation details.",
    ),
    _catalog_entry(
        "nc_evp",
        "NC eVP",
        "state_local",
        "North Carolina statewide public solicitations including schools, utilities, airports, and authorities",
        "public_portal_links",
        "https://evp.nc.gov/solicitations/",
        portal_gated=True,
        access_note="NC eVP uses a Dynamics/Power Pages data grid; use an official API configuration or browser/session adapter for live solicitation rows.",
    ),
    _catalog_entry(
        "va_dot",
        "VDOT",
        "state_dot",
        "Virginia transportation bids and proposals",
        "public_bid_page",
        "http://cabb.virginiadot.org/",
        job_params={
            "candidate_selectors": ["tr.Aqua_VDOTDataTD"],
            "title_column": 11,
            "due_date_column": 6,
            "source_url_column": 2,
            "estimated_value_column": 10,
            "title_template": "VDOT {col2}: {col11}",
            "description_prefix": "VDOT CABB advertised project.",
            "require_keywords": True,
            "require_procurement_terms": False,
            "limit": 50,
        },
    ),
    _catalog_entry(
        "az_dot",
        "ADOT",
        "state_dot",
        "Arizona transportation procurement and construction opportunities",
        "public_bid_page",
        "https://apps.azdot.gov/cnsaws/current",
        job_params={
            "candidate_selectors": ["tr"],
            "title_column": 9,
            "due_date_column": 6,
            "source_url_column": 4,
            "title_template": "ADOT {col4} {col5}: {col9}",
            "description_prefix": "ADOT current advertised project.",
            "require_keywords": True,
            "require_procurement_terms": False,
            "limit": 25,
        },
    ),
    _catalog_entry(
        "tva_procurement",
        "TVA",
        "utility",
        "Tennessee Valley Authority supplier and sourcing opportunities",
        "public_portal_links",
        "https://www.tva.com/information/suppliers",
        portal_gated=True,
        access_note="TVA supplier pages are protected by a browser challenge from server-side monitors.",
    ),
    _catalog_entry(
        "bpa_procurement",
        "BPA",
        "utility",
        "Bonneville Power Administration acquisition opportunities",
        "public_portal_links",
        "https://www.bpa.gov/energy-and-services/customers-and-contractors/buying-or-selling-products-and-services",
        access_note="BPA publishes supplier instructions and procurement category documents; open opportunity detail is often routed through federal channels.",
        covered_by_source="sam_gov",
    ),
    _catalog_entry(
        "ladwp",
        "LADWP",
        "utility",
        "Los Angeles Department of Water and Power opportunities through regional procurement portals",
        "directory_only",
        "https://www.ladwp.com/doing-business-ladwp/vendors-and-bidders",
        access_note="LADWP public procurement is covered through Los Angeles RAMP where available; direct vendor pages are directory/instructions.",
        covered_by_source="la_ramp",
    ),
    _catalog_entry(
        "austin_energy",
        "Austin Energy",
        "utility",
        "Austin Energy and City of Austin procurement",
        "public_portal_links",
        "https://austinenergy.com/contractors/working-with-austin-energy/rfps",
        job_params={
            "keywords": ["rfp", "proposal", "energy", "power", "battery storage", "solar", "wind", "epc"],
            "procurement_terms": ["rfp", "proposal"],
            "url_patterns": [r"/rfps/(All-Resource-RFP|Landfill-Solar-RFP|Wind-Energy-Resources-RFP)$"],
            "limit": 10,
        },
    ),
    _catalog_entry(
        "cps_energy",
        "CPS Energy",
        "utility",
        "San Antonio CPS Energy procurement opportunities",
        "public_portal_links",
        "https://www.cpsenergy.com/content/corporate/en/work-with-us/procurement-and-suppliers/bid-opportunities.html",
        portal_gated=True,
        access_note="CPS Energy directs active opportunities to its supplier management system.",
    ),
    _catalog_entry(
        "jea",
        "JEA",
        "utility",
        "Jacksonville JEA procurement opportunities",
        "jea_procurement",
        "https://www.jea.com/about/procurement/formal_procurement_opportunities/?ns=y",
    ),
    _catalog_entry(
        "srp",
        "SRP",
        "utility",
        "Salt River Project procurement and supplier opportunities",
        "public_portal_links",
        "https://www.srpnet.com/about/suppliers",
        portal_gated=True,
        access_note="SRP supplier pages are protected by a browser challenge from server-side monitors.",
    ),
    _catalog_entry(
        "port_authority_ny_nj",
        "Port Authority NY/NJ",
        "airport_authority",
        "Airport, port, and transit authority bid opportunities",
        "public_bid_page",
        "https://www.panynj.gov/content/port-authority/en/business-opportunities/solicitations-advertisements/Construction.model.json",
        job_params={
            "parse_json_html": True,
            "json_html_fields": ["text"],
            "candidate_selectors": ["tr"],
            "title_column": 2,
            "due_date_column": 1,
            "status_column": 1,
            "source_url_column": 0,
            "title_template": "PANYNJ {col0}: {col2}",
            "description_prefix": "Port Authority NY/NJ construction solicitation.",
            "require_keywords": False,
            "require_procurement_terms": False,
            "limit": 30,
        },
    ),
    _catalog_entry(
        "la_metro",
        "LA Metro",
        "transit",
        "Los Angeles Metro procurement opportunities",
        "public_portal_links",
        "https://business.metro.net/webcenter/portal/VendorPortal/pages_home/solicitations/openSolicitations.",
        portal_gated=True,
        access_note="LA Metro exposes a JavaScript procurement portal that needs a browser session for opportunity details.",
        job_params={"verify_tls": False},
    ),
    _catalog_entry(
        "septa",
        "SEPTA",
        "transit",
        "Southeastern Pennsylvania Transportation Authority procurement",
        "public_bid_page",
        "https://wwww.septa.org/procurement/bids/",
        job_params={
            "candidate_selectors": ["li.entry-title"],
            "title_template": "SEPTA {raw_text}",
            "description_prefix": "SEPTA open bid/RFP listing.",
            "require_keywords": True,
            "require_procurement_terms": False,
            "limit": 25,
        },
    ),
    _catalog_entry(
        "ny_mta",
        "MTA",
        "transit",
        "New York MTA procurement opportunities",
        "public_portal_links",
        "https://new.mta.info/doing-business-with-us/procurement",
        portal_gated=True,
        access_note="MTA procurement pages return an Akamai denial to server-side monitors.",
    ),
    _catalog_entry(
        "dfw_airport",
        "DFW Airport",
        "airport_authority",
        "Dallas Fort Worth Airport procurement opportunities",
        "bonfire_portal",
        "https://dfwairport.bonfirehub.com/portal/?tab=openOpportunities",
    ),
    _catalog_entry(
        "uc_procurement",
        "University of California",
        "university",
        "University of California construction and procurement opportunities",
        "public_portal_links",
        "https://procurement.ucop.edu/calusource/login",
        portal_gated=True,
        access_note="UC systemwide sourcing routes through CalUsource; use approved CalUsource/vendor access for live opportunities.",
    ),
    _catalog_entry(
        "houston_water",
        "Houston Public Works",
        "water_authority",
        "Houston water, wastewater, and public works solicitations",
        "public_portal_links",
        "https://www.beaconbid.com/solicitations/city-of-houston/open",
        portal_gated=True,
        access_note="Houston open solicitations route through BeaconBid, which presents AWS WAF/captcha to server-side monitors; use vendor/API access where permitted.",
    ),
]

DEFAULT_PUBLIC_BID_JOBS = [
    {
        "adapter": "sam_gov",
        "requires_setting": "sam_gov_api_key",
        "params": {
            "job_label": "sam_gov",
            "limit": 50,
            "source_limit": 20,
            "posted_window_days": 90,
            "ptype": "o",
            "status": "active",
            "keyword": "electrical cable OR high voltage OR medium voltage OR substation OR conduit OR transformer OR data center OR hyperscale",
            "keyword_queries": [
                "hyperscale data center",
                "AI infrastructure power",
                "GPU data center",
                "data center substation",
                "data center power",
                "critical power switchgear",
                "substation",
                "medium voltage",
                "high voltage",
                "electrical cable",
                "underground cable",
                "conduit",
                "transformer",
                "switchgear",
            ],
            "query_pause_seconds": 0.35,
            "keywords": SAM_GOV_ELECTRICAL_SOURCE_KEYWORDS,
            "require_keywords": True,
            "replace_source_records": True,
            "update_existing": True,
        },
    },
    {
        "adapter": "pjm_project_construction",
        "params": {
            "job_label": "pjm_project_construction",
            "limit": 35,
            "source_limit": 20000,
            "min_cost_millions": 5,
            "keywords": [
                "transmission",
                "substation",
                "transformer",
                "breaker",
                "high voltage",
                "230",
                "345",
                "500",
                "765",
                "data center",
                "load growth",
                "reliability",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "caiso_interconnection_queue",
        "params": {
            "job_label": "caiso_interconnection_queue",
            "limit": 30,
            "min_mw": 100,
            "min_voltage_kv": 70,
            "keywords": [
                "storage",
                "battery",
                "solar",
                "transmission",
                "interconnection",
                "substation",
                "500",
                "230",
                "data center",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "ercot_capacity_changes",
        "params": {
            "job_label": "ercot_capacity_changes",
            "limit": 30,
            "min_mw": 100,
            "keywords": [
                "data center",
                "battery",
                "storage",
                "solar",
                "wind",
                "gas",
                "interconnection",
                "planned capacity",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "iso_ne_interconnection_queue",
        "params": {
            "job_label": "iso_ne_interconnection_queue",
            "limit": 35,
            "min_mw": 75,
            "keywords": [
                "battery",
                "storage",
                "solar",
                "wind",
                "offshore wind",
                "substation",
                "interconnection",
                "115",
                "345",
                "transmission",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "miso_eras_interconnection",
        "params": {
            "job_label": "miso_eras_interconnection",
            "limit": 35,
            "min_mw": 75,
            "keywords": [
                "data center",
                "large load",
                "substation",
                "interconnection",
                "transmission",
                "115",
                "138",
                "230",
                "345",
                "500",
                "battery",
                "storage",
                "solar",
                "wind",
                "gas",
                "combined cycle",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "nyiso_interconnection_queue",
        "params": {
            "job_label": "nyiso_interconnection_queue",
            "limit": 35,
            "min_mw": 75,
            "keywords": [
                "data center",
                "load",
                "substation",
                "interconnection",
                "transmission",
                "115",
                "138",
                "230",
                "345",
                "battery",
                "storage",
                "wind",
                "offshore wind",
                "solar",
                "generation",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "spp_gi_active_requests",
        "params": {
            "job_label": "spp_gi_active_requests",
            "limit": 35,
            "min_mw": 75,
            "keywords": [
                "battery",
                "storage",
                "solar",
                "wind",
                "hybrid",
                "substation",
                "interconnection",
                "115",
                "230",
                "345",
                "transmission",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "virginia_scc_transmission_cases",
        "params": {
            "job_label": "virginia_scc_transmission_cases",
            "limit": 35,
            "source_limit": 300,
            "keywords": [
                "data center",
                "technology zone",
                "loudoun",
                "prince william",
                "culpeper",
                "substation",
                "transmission",
                "500 kV",
                "230 kV",
                "500",
                "230",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "georgia_psc_data_center",
        "params": {
            "job_label": "georgia_psc_data_center",
            "keywords": [
                "data center",
                "large-load",
                "large load",
                "georgia power",
                "generation",
                "docket",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "texas_puc_dockets",
        "params": {
            "job_label": "texas_puc_dockets",
            "limit": 30,
            "source_limit": 800,
            "keywords": [
                "certificate of convenience",
                "necessity",
                "ccn",
                "transmission",
                "transmission cost recovery",
                "substation",
                "interconnection",
                "large load",
                "data center",
                "765 kv",
                "345 kv",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "loudoun_land_applications",
        "params": {
            "job_label": "loudoun_land_applications",
            "limit": 30,
            "source_limit": 500,
            "statuses": ["In Review", "Approved"],
            "keywords": [
                "data center",
                "datacenter",
                "industrial park",
                "power generation",
                "substation",
                "transmission",
            ],
            "update_existing": True,
        },
    },
    {
        "adapter": "txdot_bid_items",
        "params": {
            "job_label": "txdot_bid_items",
            "limit": 50,
            "source_limit": 5000,
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "update_existing": True,
        },
    },
    {
        "adapter": "pa_emarketplace",
        "params": {
            "job_label": "pa_emarketplace",
            "limit": 50,
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "update_existing": True,
        },
    },
    {
        "adapter": "nypa",
        "requires_setting": "nypa_api_subscription_key",
        "params": {
            "job_label": "nypa",
            "limit": 50,
            "update_existing": True,
        },
    },
    {
        "adapter": "nyc_city_record",
        "params": {
            "job_label": "nyc_city_record",
            "limit": 25,
            "source_limit": 300,
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "update_existing": True,
        },
    },
    {
        "adapter": "nyc_city_record",
        "params": {
            "job_label": "nyc_school_construction_authority",
            "source": "nyc_school_construction_authority",
            "source_type": "education",
            "limit": 25,
            "source_limit": 300,
            "agency_keywords": ["School Construction Authority"],
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "update_existing": True,
        },
    },
    {
        "adapter": "sf_open_bids",
        "params": {
            "job_label": "sf_open_bids",
            "limit": 25,
            "source_limit": 300,
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "update_existing": True,
        },
    },
    {
        "adapter": "public_json_feed",
        "params": {
            "job_label": "la_ramp",
            "source": "la_ramp",
            "source_type": "state_local",
            "url": "https://data.lacity.org/resource/hf3r-utnq.json",
            "location": "Los Angeles, CA",
            "state": "CA",
            "agency_prefix": "Los Angeles RAMP",
            "limit": 50,
            "source_limit": 500,
            "order": "closedate ASC",
            "query_params": {
                "$where": "stagename in('Open', 'Amended')",
            },
            "mapping": {
                "title": "title",
                "agency": "department",
                "due_date": "closedate",
                "bid_status": "stagename",
                "source_url": "url.url",
            },
            "description_template": (
                "RAMP ID: {rampid}\n"
                "Department: {department}\n"
                "Category: {category}\n"
                "Type: {type}\n"
                "Status: {stagename}\n"
                "Open date: {bidpost}"
            ),
            "keyword_fields": ["title", "category", "type"],
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "status_allow": ["open", "amended"],
            "update_existing": True,
        },
    },
    {
        "adapter": "public_json_feed",
        "params": {
            "job_label": "montgomery_md_solicitations",
            "source": "montgomery_md_solicitations",
            "source_type": "state_local",
            "url": "https://data.montgomerycountymd.gov/resource/eeq6-nnwe.json",
            "location": "Montgomery County, MD",
            "state": "MD",
            "agency_prefix": "Montgomery County, MD",
            "limit": 25,
            "source_limit": 300,
            "order": "closingdate ASC",
            "query_params": {
                "$where": "status = 'Active'",
            },
            "mapping": {
                "title": "description",
                "agency": "department",
                "due_date": "closingdate",
                "bid_status": "status",
            },
            "source_url_template": "https://data.montgomerycountymd.gov/Government/Solicitations/eeq6-nnwe?number={number}",
            "description_template": (
                "Solicitation number: {number}\n"
                "Type: {type}\n"
                "Department: {department}\n"
                "Buyer: {buyer}\n"
                "Department contact: {deptcontact}\n"
                "Construction solicitation: {construction}\n"
                "LSBRP: {lsbrpindicator}"
            ),
            "keyword_fields": ["description", "department", "type"],
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "status_allow": ["active"],
            "update_existing": True,
        },
    },
    {
        "adapter": "chicago_solicitations",
        "params": {
            "job_label": "chicago_solicitations",
            "limit": 25,
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "update_existing": True,
        },
    },
    {
        "adapter": "jea_procurement",
        "params": {
            "job_label": "jea",
            "source": "jea",
            "source_type": "utility",
            "agency": "JEA",
            "state": "FL",
            "location": "Jacksonville, FL",
            "limit": 25,
            "source_limit": 1200,
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "update_existing": True,
        },
    },
    {
        "adapter": "bonfire_portal",
        "params": {
            "job_label": "dfw_airport",
            "source": "dfw_airport",
            "source_type": "airport_authority",
            "agency": "DFW Airport",
            "state": "TX",
            "location": "Dallas-Fort Worth, TX",
            "portal_url": "https://dfwairport.bonfirehub.com/portal/?tab=openOpportunities",
            "limit": 25,
            "source_limit": 250,
            "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
            "update_existing": True,
        },
    },
]

PORTAL_SOURCE_STATES = {
    "ca_dot": "CA",
    "fl_dot": "FL",
    "ny_dot": "NY",
    "ga_dot": "GA",
    "il_dot": "IL",
    "oh_dot": "OH",
    "nc_evp": "NC",
    "va_dot": "VA",
    "az_dot": "AZ",
    "ladwp": "CA",
    "austin_energy": "TX",
    "cps_energy": "TX",
    "jea": "FL",
    "srp": "AZ",
    "port_authority_ny_nj": "NY",
    "la_metro": "CA",
    "septa": "PA",
    "ny_mta": "NY",
    "dfw_airport": "TX",
    "uc_procurement": "CA",
    "houston_water": "TX",
}

DEFAULT_PUBLIC_BID_JOBS.extend(
    [
        {
            "adapter": "public_portal_links",
            "params": {
                "job_label": catalog["source"],
                "source": catalog["source"],
                "source_type": catalog["category"],
                "url": catalog["source_url"],
                "label": catalog["label"],
                "agency": catalog["label"],
                "state": PORTAL_SOURCE_STATES.get(catalog["source"]),
                "limit": 25,
                "source_limit": 600,
                "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
                "update_existing": True,
                **(catalog.get("job_params") or {}),
            },
        }
        for catalog in DEFAULT_SOURCE_CATALOG
        if catalog.get("adapter") == "public_portal_links"
        and catalog.get("source_url")
        and not catalog.get("portal_gated")
        and not catalog.get("covered_by_source")
        and not catalog.get("directory_only")
    ]
)

DEFAULT_PUBLIC_BID_JOBS.extend(
    [
        {
            "adapter": "public_bid_page",
            "params": {
                "job_label": catalog["source"],
                "source": catalog["source"],
                "source_type": catalog["category"],
                "url": catalog["source_url"],
                "label": catalog["label"],
                "agency": catalog["label"],
                "state": PORTAL_SOURCE_STATES.get(catalog["source"]),
                "limit": 25,
                "source_limit": 800,
                "keywords": DEFAULT_ELECTRICAL_SOURCE_KEYWORDS,
                "update_existing": True,
                **(catalog.get("job_params") or {}),
            },
        }
        for catalog in DEFAULT_SOURCE_CATALOG
        if catalog.get("adapter") == "public_bid_page"
        and catalog.get("source_url")
        and not catalog.get("portal_gated")
        and not catalog.get("covered_by_source")
        and not catalog.get("directory_only")
    ]
)


def missing_required_setting(settings: Any, job_spec: dict[str, Any]) -> str | None:
    required = job_spec.get("requires_setting")
    if required == "sam_gov_api_key" and (getattr(settings, "sam_gov_api_key", None) or getattr(settings, "sam_gov_api_key_secret_arn", None)):
        return None
    if required and not getattr(settings, str(required), None):
        return str(required)
    return None


def available_default_public_bid_jobs(settings: Any) -> list[dict[str, Any]]:
    return [job for job in DEFAULT_PUBLIC_BID_JOBS if missing_required_setting(settings, job) is None]


def skipped_default_public_bid_jobs(settings: Any) -> list[dict[str, Any]]:
    return [job for job in DEFAULT_PUBLIC_BID_JOBS if missing_required_setting(settings, job) is not None]
